### ISSUE TITLE
Null reference error during add-migration with EFCore5.01

### ISSUE THREAD

**Issue by msawczyn** [efcore/EFCore.CheckConstraints#15]
Hi Shay,

With 5.0.0, I'm getting a null reference exception adding a migration to an EFCore 5.01 context under .NET5. Target database is SQLServer.

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at EFCore.CheckConstraints.Internal.CheckConstraintsOptionsExtension.ExtensionInfo.PopulateDebugInfo(IDictionary`2 debugInfo)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>g__BuildServiceProvider|3()
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>b__2(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at Include.Domain.Models.Context.IncludeContext..ctor(DbContextOptions`1 options) in C:\Code\_Clients\AWH\IH\include-api\Include.Domain\Models\Context\Generated\IncludeContext.generated.cs:line 259
   at Include.Domain.Models.Context.IncludeContextFactory.CreateDbContext(String[] args) in C:\Code\_Clients\AWH\IH\include-api\Include.Domain\Models\Context\Generated\IncludeContextFactory.generated.cs:line 47
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory, Type contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_2.<FindContextTypes>b__9()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

No issues with 5.0.0-rc1.1; I've had to downgrade back to that one.

**Comment by roji** [comment]
Sorry for not looking at this earlier. I've merged this and will release a 5.0.1 soon.
